[env:nanoatmega328]
platform = atmelavr@5.1.0
board = nanoatmega328
framework = arduino
monitor_speed = 9600
build_flags =
  -I include
check_flags =
  cppcheck: --suppress=*:*/.pio/libdeps/*
platform_packages =
  platformio/framework-arduino-avr@5.2.0
  platformio/toolchain-atmelavr@1.70300.191015
lib_deps =
  featherfly/SoftwareSerial @ 1.0
